import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const moneyStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        paddingTop: Platform.OS === 'ios' ? 70 : 50,
        paddingBottom: 40,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: '900',
        color: 'white',
        letterSpacing: -0.5,
        textAlign: 'center',
    },
    headerSubtitle: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.8)',
        marginTop: 4,
        fontWeight: '500',
        textAlign: 'center',
    },
    balanceHeader: {
        marginHorizontal: 20,
        marginTop: -35,
        borderRadius: 30,
        padding: 28,
        backgroundColor: '#1e293b',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 15,
    },
    headerLabel: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    headerBalance: {
        color: 'white',
        fontSize: 40,
        fontWeight: '900',
        marginTop: 8,
    },
    bankTag: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.1)',
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 100,
        marginTop: 16,
        gap: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    bankTagName: {
        color: 'white',
        fontSize: 12,
        fontWeight: '700',
    },
    actionsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingHorizontal: 20,
        marginTop: 24,
        marginBottom: 32,
    },
    actionItem: {
        alignItems: 'center',
        width: 80,
    },
    actionIcon: {
        width: 60,
        height: 60,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
        backgroundColor: 'white',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    actionLabel: {
        fontSize: 11,
        fontWeight: '800',
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    section: {
        flex: 1,
        backgroundColor: 'white',
        borderTopLeftRadius: 40,
        borderTopRightRadius: 40,
        paddingHorizontal: 20,
        paddingTop: 32,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: '#0f172a',
        marginBottom: 20,
    },
    transactionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        marginBottom: 8,
    },
    txAvatar: {
        width: 52,
        height: 52,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    txInfo: {
        flex: 1,
        marginLeft: 16,
    },
    txName: {
        fontSize: 16,
        fontWeight: '800',
        color: '#1e293b',
    },
    txDate: {
        fontSize: 13,
        color: '#94a3b8',
        marginTop: 2,
        fontWeight: '500',
    },
    txAmount: {
        fontSize: 17,
        fontWeight: '900',
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 60,
    },
    emptyText: {
        color: '#94a3b8',
        fontSize: 15,
        marginTop: 12,
        fontWeight: '700',
    },
    // Modal & Transfer Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: 'white',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#1e293b',
    },
    modalBody: {
        gap: 16,
    },
    inputLabel: {
        fontSize: 12,
        fontWeight: '800',
        color: '#64748b',
        marginBottom: 4,
        marginTop: 12,
    },
    helperText: {
        fontSize: 11,
        color: '#94a3b8',
        marginTop: 4,
    },
    primaryBtnText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '800',
    },
    bankItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    bankIcon: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: '#f1f5f9',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    bankName: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1e293b',
    },
    bankCode: {
        fontSize: 12,
        color: '#94a3b8',
    },
    transferHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    transferHeaderTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#1e293b',
    },
    stepTitle: {
        fontSize: 28,
        fontWeight: '900',
        color: '#0f172a',
        marginBottom: 8,
    },
    stepSubtitle: {
        fontSize: 16,
        color: '#64748b',
        marginBottom: 32,
    },
    searchBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f1f5f9',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 14,
        gap: 12,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#1e293b',
        fontWeight: '600',
    },
    goBtn: {
        color: '#1e293b',
        fontWeight: '800',
        fontSize: 16,
    },
    userDisplay: {
        alignItems: 'center',
        marginBottom: 40,
    },
    userAvatarLarge: {
        width: 100,
        height: 100,
        borderRadius: 35,
        backgroundColor: '#f1f5f9',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    avatarTextLarge: {
        color: '#1e293b',
        fontSize: 40,
        fontWeight: '900',
    },
    userNameLarge: {
        fontSize: 24,
        fontWeight: '900',
        color: '#1e293b',
    },
    userPhoneLarge: {
        fontSize: 16,
        color: '#64748b',
        marginTop: 4,
    },
    amountBox: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
    },
    currencySymbol: {
        fontSize: 48,
        fontWeight: '900',
        color: '#0f172a',
    },
    amountInput: {
        fontSize: 64,
        fontWeight: '900',
        color: '#0f172a',
        marginLeft: 8,
    },
    noteInput: {
        backgroundColor: '#f8fafc',
        padding: 20,
        borderRadius: 20,
        fontSize: 16,
        color: '#1e293b',
        marginBottom: 32,
        textAlign: 'center',
        fontWeight: '600',
    },
    successCircle: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#22c55e',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 24,
    },
    successTitle: {
        fontSize: 32,
        fontWeight: '900',
        color: '#0f172a',
    },
    successSubtitle: {
        fontSize: 16,
        color: '#64748b',
        marginTop: 8,
    },
    fab: {
        position: 'absolute',
        bottom: 30,
        right: 30,
        width: 64,
        height: 64,
        borderRadius: 24,
        backgroundColor: '#1e293b',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
    },
    transferContainer: {
        flex: 1,
        backgroundColor: '#fff',
    },
    stepContainer: {
        flex: 1,
        padding: 24,
        paddingTop: 40,
    },
    primaryBtn: {
        backgroundColor: '#1e293b',
        padding: 20,
        borderRadius: 20,
        alignItems: 'center',
        marginTop: 20,
    },
    input: {
        backgroundColor: '#f1f5f9',
        padding: 18,
        borderRadius: 18,
        fontSize: 16,
        color: '#1e293b',
        fontWeight: '600',
        marginBottom: 16,
    },
});
